---
#- name: install nginx
#  become: yes
#  apt:
#    name: nginx
#    state: present
#  notify:
#    - enable nginx

#- name: delete default
#  become: yes
#  file:
#    path: /etc/nginx/sites-enabled/default
#    state: absent

- name: create index
  template:
    src: templates/index.html.j2
    dest: /home/rincewind/"{{ item }}"
  loop: "{{ nginx_sitename }}"
