---
- name: install nginx
  become: yes
  apt:
    name: nginx
    state: present
  notify:
    - enable nginx

- name: delete default
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
    
 
